# Generated by Django 3.0.8 on 2020-09-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20200731_2009'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialPost',
            new_name='Post',
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ManyToManyField(to='inventario.CategoriaInvModel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Post')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.ProveedorModel')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
