# Generated by Django 3.0.8 on 2020-09-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20200731_2009'),
        ('inventario', '0002_auto_20200905_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ManyToManyField(to='inventario.CategoriaInvModel')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.ProveedorModel')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='post',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
