# Generated by Django 3.0.8 on 2020-09-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_historicalarticulomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('vendidos', models.IntegerField()),
                ('precio', models.CharField(max_length=100)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
