# Generated by Django 3.0.8 on 2020-10-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20201001_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasmodel',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ventasmodel',
            name='articulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventario.ArticuloModel'),
        ),
    ]
