# Generated by Django 3.0.8 on 2020-10-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20201002_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodel',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ArticuloModel'),
        ),
    ]
