# Generated by Django 3.0.8 on 2020-08-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('garantia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantiamodel',
            name='cliente',
        ),
        migrations.AddField(
            model_name='garantiamodel',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cliente.ClienteModel'),
        ),
    ]
