# Generated by Django 3.0.8 on 2020-08-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedormodel',
            old_name='direccion',
            new_name='descripcion',
        ),
    ]
