# Generated by Django 3.0.8 on 2020-08-03 00:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono_uno', phone_field.models.PhoneField(max_length=31)),
                ('telefono_dos', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creacion'],
            },
        ),
    ]
