# Generated by Django 3.0.8 on 2020-08-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_profile_correo'),
        ('servicios', '0002_remove_serviciomodel_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='tecnico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='registration.Profile'),
        ),
    ]
